// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMtaOperationLogsParams creates a new GetMtaOperationLogsParams object
// with the default values initialized.
func NewUpdateAccessTokenForOperationParams() *UpdateAccessTokenForOperationParams {
	var ()
	return &UpdateAccessTokenForOperationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMtaOperationLogsParamsWithTimeout creates a new GetMtaOperationLogsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAccessTokenForOperationParamsWithTimeout(timeout time.Duration) *UpdateAccessTokenForOperationParams {
	var ()
	return &UpdateAccessTokenForOperationParams{

		timeout: timeout,
	}
}

// NewGetMtaOperationLogsParamsWithContext creates a new GetMtaOperationLogsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAccessTokenForOperationParamsWithContext(ctx context.Context) *UpdateAccessTokenForOperationParams {
	var ()
	return &UpdateAccessTokenForOperationParams{

		Context: ctx,
	}
}

// NewGetMtaOperationLogsParamsWithHTTPClient creates a new GetMtaOperationLogsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAccessTokenForOperationParamsWithHTTPClient(client *http.Client) *UpdateAccessTokenForOperationParams {
	var ()
	return &UpdateAccessTokenForOperationParams{
		HTTPClient: client,
	}
}

/*GetMtaOperationLogsParams contains all the parameters to send to the API endpoint
for the get mta operation logs operation typically these are written to a http.Request
*/
type UpdateAccessTokenForOperationParams struct {

	/*OperationID*/
	OperationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get mta operation logs params
func (o *UpdateAccessTokenForOperationParams) WithTimeout(timeout time.Duration) *UpdateAccessTokenForOperationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get mta operation logs params
func (o *UpdateAccessTokenForOperationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get mta operation logs params
func (o *UpdateAccessTokenForOperationParams) WithContext(ctx context.Context) *UpdateAccessTokenForOperationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get mta operation logs params
func (o *UpdateAccessTokenForOperationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get mta operation logs params
func (o *UpdateAccessTokenForOperationParams) WithHTTPClient(client *http.Client) *UpdateAccessTokenForOperationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get mta operation logs params
func (o *UpdateAccessTokenForOperationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOperationID adds the operationID to the get mta operation logs params
func (o *UpdateAccessTokenForOperationParams) WithOperationID(operationID string) *UpdateAccessTokenForOperationParams {
	o.SetOperationID(operationID)
	return o
}

// SetOperationID adds the operationId to the get mta operation logs params
func (o *UpdateAccessTokenForOperationParams) SetOperationID(operationID string) {
	o.OperationID = operationID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAccessTokenForOperationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param operationId
	if err := r.SetPathParam("operationId", o.OperationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
