// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	baseclient "github.com/cloudfoundry-incubator/multiapps-cli-plugin/clients/baseclient"
)

// ExecuteOperationActionReader is a Reader for the UpdateAccessTokenForOperation structure.
type UpdateAccessTokenForOperationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAccessTokenForOperationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 202:
		result := NewUpdateAccessTokenForOperationAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, baseclient.BuildErrorResponse(response, consumer, o.formats)
	}
}

// NewUpdateAccessTokenForOperationAccepted creates a UpdateAccessTokenForOperationAccepted with default headers values
func NewUpdateAccessTokenForOperationAccepted() *UpdateAccessTokenForOperationAccepted {
	return &UpdateAccessTokenForOperationAccepted{}
}

/*UpdateAccessTokenForOperationAccepted handles this case with default header values.

Accepted
*/
type UpdateAccessTokenForOperationAccepted struct {
	Location strfmt.URI
}

func (o *UpdateAccessTokenForOperationAccepted) Error() string {
	return fmt.Sprintf("[POST /operations/{operationId}/token][%d] UpdateAccessTokenForOperationAccepted ", 202)
}

func (o *UpdateAccessTokenForOperationAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {
	return nil
}
